# Generated by Django 4.2.1 on 2023-06-12 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('idSucursal', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('num_habitaciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('idTipoHabitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idHabitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numeroHabitacion', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('precioPorNoche', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('idHotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeranumApp.hotel')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeranumApp.tipohabitacion')),
            ],
            options={
                'unique_together': {('idHotel', 'numeroHabitacion')},
            },
        ),
    ]
