# Generated by Django 4.2.2 on 2023-06-28 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idHabitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numeroHabitacion', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('precioPorNoche', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('is_disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(default='static/img/habitacion-prueba.jpg', upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('idHotel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('num_habitaciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioHoteleria',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('idTipoHabitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Subservicio',
            fields=[
                ('idSubservicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=400)),
                ('horarioApertura', models.TimeField()),
                ('horarioCierre', models.TimeField()),
                ('imagen', models.ImageField(default='static/img/servicio_prueba.jpg', upload_to='static/img')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeranumApp.serviciohoteleria')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.CharField(max_length=9)),
                ('fecha_salida', models.CharField(max_length=9)),
                ('dias_estancia', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeranumApp.habitacion')),
                ('idHotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeranumApp.hotel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='idHotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeranumApp.hotel'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeranumApp.tipohabitacion'),
        ),
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together={('idHotel', 'numeroHabitacion')},
        ),
    ]
