# Generated by Django 4.2.1 on 2023-06-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipohabitacion',
            name='descripcion',
            field=models.TextField(default='THIS IS A DEFAULT TEST', max_length=400),
            preserve_default=False,
        ),
    ]
