# Generated by Django 4.2.2 on 2023-06-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0002_remove_reserva_id_reserva_idreserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
