# Generated by Django 4.2.1 on 2023-06-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0004_rename_idsucursal_hotel_idhotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(default='habitacion-prueba.jpg', upload_to='static/img'),
        ),
    ]
