# Generated by Django 4.2.1 on 2023-06-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0007_alter_habitacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='imagen',
        ),
    ]
