# Generated by Django 4.2.1 on 2023-06-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0010_serviciohoteleria_subservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciohoteleria',
            name='descripcion',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='subservicio',
            name='descripcion',
            field=models.TextField(max_length=700),
        ),
    ]
