# Generated by Django 4.2.1 on 2023-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0011_alter_serviciohoteleria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciohoteleria',
            name='descripcion',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='subservicio',
            name='descripcion',
            field=models.TextField(max_length=400),
        ),
    ]
