# Generated by Django 4.1.4 on 2023-06-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0012_alter_serviciohoteleria_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservicio',
            name='imagen',
            field=models.ImageField(default='static/img/servicio_prueba.jpg', upload_to='static/img'),
        ),
    ]
