# Generated by Django 4.2.1 on 2023-06-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0013_subservicio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciohoteleria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='serviciohoteleria',
            name='horarioApertura',
        ),
        migrations.RemoveField(
            model_name='serviciohoteleria',
            name='horarioCierre',
        ),
    ]
