# Generated by Django 4.2.1 on 2023-06-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0014_remove_serviciohoteleria_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('activado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=100)),
                ('contrasenna', models.CharField(max_length=100)),
            ],
        ),
    ]
