# Generated by Django 4.2.2 on 2023-06-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('VeranumApp', '0018_rename_usuario_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customuser',
        ),
    ]
