# Generated by Django 4.2.2 on 2023-06-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0019_rename_user_customuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='correo',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
