# Generated by Django 4.2.2 on 2023-06-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VeranumApp', '0022_alter_customuser_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customuser',
        ),
    ]
