# Generated by Django 4.2.1 on 2023-06-22 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VeranumApp', '0023_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='is_disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('dias_estancia', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeranumApp.habitacion')),
                ('idHotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeranumApp.hotel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
